name: satsang_attendance
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

  json_annotation:
  email_validator: '^1.0.0'
  google_sign_in:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_core:
  cloud_firestore:
  firebase_auth:
  local_auth:
  provider:
  get_it:
  line_awesome_flutter:
  flutter_screenutil:
  animated_theme_switcher:
  #curved_navigation_bar:
  image_picker:
  firebase_storage:
  font_awesome_flutter:

dev_dependencies:
  json_serializable:
  build_runner:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/avatar.png
    - images/
  #  - images/a_dot_ham.jpeg
  fonts:

   - family: SFProText
     fonts:
       - asset: assets/fonts/SF-Pro-Text-Thin.otf
         weight: 100
       - asset: assets/fonts/SF-Pro-Text-Regular.otf
         weight: 400
       - asset: assets/fonts/SF-Pro-Text-Medium.otf
         weight: 500
       - asset: assets/fonts/SF-Pro-Text-Bold.otf
         weight: 600
